Update logic apply loan + CI CD

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,110 +1,113 @@
-#name: Deploy Spring Boot to Ubuntu VM
-#
-#on:
-#  push:
-#    branches: [ main ]
-#
-#jobs:
-#  deploy:
-#    runs-on: ubuntu-latest
-#
-#    steps:
-#      - name: Checkout code
-#        uses: actions/checkout@v3
-#
-#      - name: Set up SSH
-#        uses: webfactory/ssh-agent@v0.8.0
-#        with:
-#          ssh-private-key: ${{ secrets.PRIVATE_KEY }}
-#
-#      - name: Deploy to VM
-#        run: |
-#          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
-#            cd ~/Solvr || { echo "❌ Directory Solvr not found"; exit 1; }
-#
-#            echo "🔪 Killing existing app..."
-#            pkill -f 'solvr-0.0.1-SNAPSHOT.jar' || true
-#
-#            echo "📥 Pulling latest code..."
-#            sudo git pull origin main
-#
-#            echo "🧹 Building the app..."
-#            sudo mvn clean package -DskipTests
-#
-#            echo "🚀 Running the app in background..."
-#            nohup java -jar target/solvr-0.0.1-SNAPSHOT.jar > solvr.log 2>&1 &
-#          EOF
-
-
-
 name: Deploy Spring Boot to Ubuntu VM
 
 on:
   push:
-    branches:
-      - main  # Sesuaikan dengan branch kamu
+    branches: [ main ]
 
 jobs:
-  build:
+  deploy:
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Set up Java
-        uses: actions/setup-java@v3
+      - name: Set up SSH
+        uses: webfactory/ssh-agent@v0.8.0
         with:
-          java-version: '21'
-          distribution: 'temurin'
+          ssh-private-key: ${{ secrets.PRIVATE_KEY }}
 
-      - name: Build Spring Boot App (Maven)
-        run: mvn clean package -DskipTests
+      - name: Deploy to VM
+        run: |
+          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
+            cd ~/Solvr || { echo "❌ Directory Solvr not found"; exit 1; }
 
+            echo "🔪 Killing existing app..."
+            pkill -f 'solvr-0.0.1-SNAPSHOT.jar' || true
+
+            echo "📥 Pulling latest code..."
+            sudo git pull origin main
+
+            echo "🧹 Building the app..."
+            sudo mvn clean package -DskipTests
+
+            echo "🚀 Running the app in background..."
+            nohup java -jar target/solvr-0.0.1-SNAPSHOT.jar > solvr.log 2>&1 &
+          EOF
+
+
+
+
+
+
+#name: Deploy Spring Boot to Ubuntu VM
+#
+#on:
+#  push:
+#    branches:
+#      - main  # Sesuaikan dengan branch kamu
+#
+#jobs:
+#  build:
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v3
+#
+#      - name: Set up Java
+#        uses: actions/setup-java@v3
+#        with:
+#          java-version: '21'
+#          distribution: 'temurin'
+#
+#      - name: Build Spring Boot App (Maven)
+#        run: mvn clean package -DskipTests
+#
+##      - name: Copy JAR to Ubuntu VM
+##        uses: appleboy/scp-action@v0.1.4
+##        with:
+##          host: ${{ secrets.SSH_HOST }}
+##          username: ${{ secrets.SSH_USER }}
+##          key: ${{ secrets.SSH_PRIVATE_KEY }}
+##          source: "target/solvr-0.0.1-SNAPSHOT.jar"
+##          target: "/var/www/solvr/app.jar"
+##
+##      - name: Restart Spring Boot App on Ubuntu VM
+##        uses: appleboy/ssh-action@v0.1.7
+##        with:
+##          host: ${{ secrets.SSH_HOST }}
+##          username: ${{ secrets.SSH_USER }}
+##          key: ${{ secrets.SSH_PRIVATE_KEY }}
+##          script: |
+##            echo "🔪 Killing existing app..."
+##            pkill -f 'app.jar' || true
+##
+##            echo "🚀 Running the app in background..."
+##            cd /var/www/solvr
+##            nohup java -jar app.jar --spring.profiles.active=prod > app.log 2>&1 &
+##            echo "✅ App deployed and running!"
+#
+#
 #      - name: Copy JAR to Ubuntu VM
 #        uses: appleboy/scp-action@v0.1.4
 #        with:
-#          host: ${{ secrets.SSH_HOST }}
-#          username: ${{ secrets.SSH_USER }}
-#          key: ${{ secrets.SSH_PRIVATE_KEY }}
-#          source: "target/solvr-0.0.1-SNAPSHOT.jar"
-#          target: "/var/www/solvr/app.jar"
+#          host: ${{ secrets.HOST}}
+#          username: ${{ secrets.USERNAME }}
+#          key: ${{ secrets.PRIVATE_KEY }}
+#          source: "target/*.jar"
+#          target: "/home/${{ secrets.USERNAME }}/solvr-test-ci-cd"
 #
 #      - name: Restart Spring Boot App on Ubuntu VM
 #        uses: appleboy/ssh-action@v0.1.7
 #        with:
-#          host: ${{ secrets.SSH_HOST }}
-#          username: ${{ secrets.SSH_USER }}
-#          key: ${{ secrets.SSH_PRIVATE_KEY }}
+#          host: ${{ secrets.HOST }}
+#          username: ${{ secrets.USERNAME }}
+#          key: ${{ secrets.PRIVATE_KEY }}
 #          script: |
-#            echo "🔪 Killing existing app..."
-#            pkill -f 'app.jar' || true
+#            pkill -f 'java' || true
+#            cd /home/${{ secrets.USERNAME }}/solvr-test-ci-cd
+#            nohup java -jar solvr-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod > app.log 2>&1 &
+#            echo "App deployed and running!"
+#            tail -f app.log
 #
-#            echo "🚀 Running the app in background..."
-#            cd /var/www/solvr
-#            nohup java -jar app.jar --spring.profiles.active=prod > app.log 2>&1 &
-#            echo "✅ App deployed and running!"
-
-
-      - name: Copy JAR to Ubuntu VM
-        uses: appleboy/scp-action@v0.1.4
-        with:
-          host: ${{ secrets.HOST}}
-          username: ${{ secrets.USERNAME }}
-          key: ${{ secrets.PRIVATE_KEY }}
-          source: "target/*.jar"
-          target: "/home/${{ secrets.USERNAME }}/solvr-test-ci-cd"
-
-      - name: Restart Spring Boot App on Ubuntu VM
-        uses: appleboy/ssh-action@v0.1.7
-        with:
-          host: ${{ secrets.HOST }}
-          username: ${{ secrets.USERNAME }}
-          key: ${{ secrets.PRIVATE_KEY }}
-          script: |
-            pkill -f 'java' || true
-            cd /home/${{ secrets.USERNAME }}/solvr-test-ci-cd
-            nohup java -jar solvr-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod > app.log 2>&1 &
-            echo "App deployed and running!"
-            tail -f app.log
-
